// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropbtn': string;
  'dropdown': string;
  'dropdownContent': string;
  'show': string;
}
export const cssExports: CssExports;
export default cssExports;
