// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkBoxContainer': string;
  'form': string;
}
export const cssExports: CssExports;
export default cssExports;
