// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  spinner: string;
  spinnerInner1: string;
  spinnerInner2: string;
  spinnerInner3: string;
}
export const cssExports: CssExports;
export default cssExports;
