// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  contentParallax: string;
  contentText: string;
  contentWrap: string;
  heading1: string;
  heading2: string;
  pockeButton: string;
  root: string;
}
export const cssExports: CssExports;
export default cssExports;
