// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  abilities: string;
  card: string;
  cardBoxSquare: string;
  cardLabel: string;
  cardTitle: string;
  cardValue: string;
  closeButton: string;
  experience: string;
  generationContainer: string;
  hp: string;
  imageConteiner: string;
  infoWrap: string;
  label: string;
  labelWrap: string;
  modal: string;
  nameConteiner: string;
  overlay: string;
  pictureWrap: string;
  statText: string;
  statValueCard: string;
  statsSum: string;
  textWrap: string;
}
export const cssExports: CssExports;
export default cssExports;
