// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeLink': string;
  'link': string;
  'logo': string;
  'nav': string;
  'root': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
