// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  footerText: string;
  h3: string;
  makeWithLove: string;
  ourTeam: string;
  pharagraph: string;
}
export const cssExports: CssExports;
export default cssExports;
