// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  documentation: string;
  groupe: string;
  groupe95: string;
  header: string;
  headerContainer: string;
  home: string;
  legendaries: string;
  line1: string;
  logo: string;
  menu: string;
  menuItem1: string;
  menuItem2: string;
  menuItem3: string;
  menuItemActive: string;
  navbar: string;
  pokedex: string;
  rectangle2: string;
  third: string;
}
export const cssExports: CssExports;
export default cssExports;
