// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  font: string;
  header: string;
  li: string;
  logo: string;
  nav: string;
  w30: string;
  w70: string;
}
export const cssExports: CssExports;
export default cssExports;
