// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  cards: string;
  cardsWrap: string;
  errow: string;
  header: string;
  headerContainer: string;
  image: string;
  item1: string;
  item2: string;
  item3: string;
  main: string;
  root: string;
  skillBox: string;
  skillsWrap: string;
  text: string;
  textContainer: string;
  textHeader: string;
}
export const cssExports: CssExports;
export default cssExports;
