// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonWrap': string;
  'headerFrom': string;
  'headerTo': string;
  'headerWrap': string;
  'input': string;
  'inputWrap': string;
  'root': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
