// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'homeDesktop': string;
  'padding': string;
}
export const cssExports: CssExports;
export default cssExports;
