// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  forFooter: string;
  homeDesktop: string;
  padding: string;
}
export const cssExports: CssExports;
export default cssExports;
