// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cardConteiner': string;
  'containerCards': string;
  'containerInput': string;
  'containerWrap': string;
  'filtersConteiner': string;
  'heading': string;
  'inputWrap': string;
  'loader': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
